env:
  commonjs: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - .
  - plugin:import/recommended
  - ./import
  - plugin:node/recommended
  - plugin:eslint-plugin/recommended
  - plugin:@typescript-eslint/recommended
  - ./typescript
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: latest
  sourceType: script
plugins:
  - '@typescript-eslint'
  - import
