env:
  commonjs: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:node/recommended
  - plugin:eslint-plugin/recommended
  - .
parserOptions:
  ecmaVersion: latest
rules: {}
