env:
  commonjs: true
  es2021: true
  node: true
extends:
  - plugin:eslint-plugin/recommended
  - ./dist/javascript
  - ./dist/import
  - ./dist/typescript
  - plugin:import/typescript
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: latest
  sourceType: module
settings:
  import/resolver: typescript
