name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  NODE_VERSION: 16

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    name: Create Release

    concurrency:
      group: ${{ github.workflow }}-github-${{ github.ref_name }}
      cancel-in-progress: true

    environment:
      name: release
      url: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}

    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - uses: actions/checkout@v3

      - name: Changelog
        uses: ardalanamini/auto-changelog@v3
        id: changelog

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ steps.changelog.outputs.prerelease }}

  publish-npm:
    name: Publish to NPM

    concurrency:
      group: ${{ github.workflow }}-npm-${{ github.ref_name }}
      cancel-in-progress: true

    environment:
      name: npm
      url: https://www.npmjs.com/package/eslint-config-noir

    runs-on: ubuntu-latest

    needs:
      - release

    steps:
      - uses: actions/checkout@v3

      - name: Use PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: pnpm i

      - name: Publish the package
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    name: Publish to GitHub Packages

    concurrency:
      group: ${{ github.workflow }}-gpr-${{ github.ref_name }}
      cancel-in-progress: true

    environment:
      name: gpr
      url: https://github.com/${{ github.repository }}/packages

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    needs:
      - release

    steps:
      - uses: actions/checkout@v3

      - name: Use PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          scope: '@ardalanamini'

      - run: sed -i 's/"name":\ "eslint-config-noir"/"name":\ "@ardalanamini\/eslint-config-noir"/g' package.json package-lock.json

      - name: Install dependencies
        run: pnpm i

      - name: Publish the package
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
